set(_AMENT_PACKAGE_NAME "appleproj_interfaces")
set(appleproj_interfaces_VERSION "0.0.0")
set(appleproj_interfaces_MAINTAINER "TBD <tbd@example.com>")
set(appleproj_interfaces_BUILD_DEPENDS "rosidl_default_generators" "builtin_interfaces" "geometry_msgs" "sensor_msgs" "std_msgs")
set(appleproj_interfaces_BUILDTOOL_DEPENDS "ament_cmake")
set(appleproj_interfaces_BUILD_EXPORT_DEPENDS "builtin_interfaces" "geometry_msgs" "sensor_msgs" "std_msgs")
set(appleproj_interfaces_BUILDTOOL_EXPORT_DEPENDS )
set(appleproj_interfaces_EXEC_DEPENDS "rosidl_default_runtime" "builtin_interfaces" "geometry_msgs" "sensor_msgs" "std_msgs")
set(appleproj_interfaces_TEST_DEPENDS )
set(appleproj_interfaces_GROUP_DEPENDS )
set(appleproj_interfaces_MEMBER_OF_GROUPS "rosidl_interface_packages")
set(appleproj_interfaces_DEPRECATED "")
set(appleproj_interfaces_EXPORT_TAGS)
list(APPEND appleproj_interfaces_EXPORT_TAGS "<build_type>ament_cmake</build_type>")
