<?xml version="1.0"?>
<package format="3">
  <name>appleproj_personal_pc2</name>
  <version>0.0.0</version>
  <description>Monitoring and inspection retry tools for Personal PC 2.</description>
  <maintainer email="tbd@example.com">TBD</maintainer>
  <license>TBD</license>

  <buildtool_depend>ament_python</buildtool_depend>

  <exec_depend>appleproj_interfaces</exec_depend>
  <exec_depend>launch</exec_depend>
  <exec_depend>launch_ros</exec_depend>
  <exec_depend>rclpy</exec_depend>

  <test_depend>python3-pytest</test_depend>

  <export>
    <build_type>ament_python</build_type>
  </export>
</package>
